---
# tasks file for docker

# Install other packages and tools
- name: Enable EPEL Repository on CentOS 7
  yum:
    name: epel-release
    state: latest
  become: true
  when: ansible_distribution == 'CentOS'

- name: Install basic tools & packages
  package:
    name:
      - make
      - git
      - nano
      - vim
      - emacs
      - python3-pip
      - tree
      - byobu
      - screen
     # - moreutils # for gat-cli
    state: latest

- name: Enable byobu for users (forcing them into a Screen/TMUX session on login via ssh)
  command: byobu-launcher-install
  become: true
  become_user: centos
  when: ansible_distribution == 'CentOS'

- name: Configure a MOTD (message of the day task)
  copy:
    content: "{{ motd_centos }}"
    dest: /etc/motd
  notify: MOTD changed
  when: ansible_distribution == "CentOS"

- name: Requisites of Docker, Install yum-utils device mapper, and lvm2 
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: present
    update_cache: true
  notify: Requisites of docker installed
  when: ansible_distribution == 'CentOS'

- name: Add docker repository
  yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable - $basearch
    baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
    enabled: yes
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg
  when: ansible_distribution == 'CentOS'

- name: Install docker-ce from stable repository
  yum:
    name: docker-ce
    update_cache: yes
    state: latest
  when: ansible_distribution == 'CentOS'

# - name: Display docker version
#   command: docker --version

- name: Configure a MOTD (message of the day task)
  copy:
    content: "{{ motd_ubuntu }}"
    dest: /etc/motd
  notify: MOTD changed
  when: ansible_distribution == "Ubuntu"


...